/*
 * Copyright (c) 2008-2016, Integrity Project Ltd. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of the Integrity Project nor the names of its contributors
 * may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE
 */

#ifndef __TBA_STL_PE_NT_DIRECTORY_RELOC_H
#define __TBA_STL_PE_NT_DIRECTORY_RELOC_H

/*
 * ntDirReloc.h
 *
 * Operation over PE relocation table.
 *
 * Author: Tal Harel
 */
#include "xStl/types.h"
#include "xStl/data/array.h"
#include "xStl/data/list.h"
#include "xStl/data/string.h"
#include "xStl/stream/basicIO.h"
#include "xStl/stream/stringerStream.h"
#include "pe/ntdir.h"
#include "pe/section.h"
#include "pe/datastruct.h"
#include "pe/ntheader.h"

/*
 * Forward declaration for output streams
 */
/*
#ifdef PE_TRACE
class cNtDirReloc;
cStringerStream& operator << (cStringerStream& out,
                              const cNtDirReloc& object);
#endif // PE_TRACE
*/

/*
 * Handles the ".reloc" section - The relocation table section.
 * Read the section from stream. Provide a set of access utilities and allow
 * to write-back the reloc section.
 */
class cNtDirReloc : public cNtDirectory {
public:
    /*
     * Default constructor.
     */
    cNtDirReloc();

    /*
     * Read the .reloc section from a PE image.
     *
     * header - The NT-header descriptor of the PE file.
     *
     * NOTE: This function extract from the NT-header the location of the reloc
     *       directory and use the auto-generated 'VirtualMemoryAccesser' in
     *       order to access the reloc directory and extract the information
     *       from
     *
     * Throw exception if the header doesn't contain a reference for the memory
     * of the PE file.
     */
    cNtDirReloc(cNtHeader& header);

    /*
     * Reads the reloc table from a stream
     *
     * stream - The stream to read the information from.
     */
    void read(basicInput& stream);

    /*
     * See cNtDirectory::isMyDir
     * Return true on the IMAGE_DIRECTORY_ENTRY_BASERELOC
     */
    virtual bool isMyDir(uint directoryTypeIndex);

    /*
     * See cNtDirectory::readDirectory
     * See cNtDirectory::cNtDirectory(const cNtHeader&)
     */
    virtual void readDirectory(const cNtHeader& image,
                               uint directoryTypeIndex = UNKNOWNDIR);

    /*
     * Describe a single offset entry within the reloc directory.
     *
     * Author: Tal Harel
     */
    class cRelocEntry : public cSerializedObject {
    public:
        // Constructor, copy-constructor, operator = will auto-generated by the
        // compiler

        /*
         * Overrides the '>' operator for this class, to be able to sort
         * reloc offsets according to their addresses
         */
        bool operator > (const cNtDirReloc::cRelocEntry &other) const;

        // The virtual (relative) address of the reloc offset
        remoteAddressNumericValue m_offsetAddress;
        // The virtual (relative) address of the content the offset points to
        //remoteAddressNumericValue m_contentAddress;

        // See cSerializedObject::isValid.
        virtual bool isValid() const;
        // See cSerializedObject::serialize.
        virtual void serialize(basicOutput& stream) const;
        // See cSerializedObject::deserialize.
        virtual void deserialize(basicInput& stream);
    };
    typedef cArray<cRelocEntry> RelocTable;

    /*
     * Returns the export table
     */
    const RelocTable& getRelocArray() const;

private:
    // Private members

    // Deny copy-constructor and operator =
    cNtDirReloc(const cNtDirReloc& other);
    cNtDirReloc& operator = (const cNtDirReloc& other);

    // The friendly trace
    /*
    #ifdef PE_TRACE
    friend cStringerStream& operator << (cStringerStream& out,
                                         const cNtDirReloc& object);
    #endif //PE_TRACE
    */

    // A list of all relocated offsets
    RelocTable m_relocOffsets;
};

#endif // __TBA_STL_PE_NT_DIRECTORY_RELOC_H
